# Copyright (C) 2024 SUSE LLC <petr.pavlu@suse.com>
# SPDX-License-Identifier: GPL-2.0-or-later

[package]
name = "suse-kabi-tools"
version = "0.1.0"
authors = ["Petr Pavlu <petr.pavlu@suse.com>"]
edition = "2021"
